server:
  port: 29880

spring:
  application:
    name: Cloud-payment-service
  zipkin:
    base-url: http://192.168.2.3:9411
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.3:3306/springcloud20200413?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  sleuth:
    sampler: # 采样率
      probability: 1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.2.13:27020/eureka/
  instance:
    instance-id: payment29880
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entity

management:
  endpoints:
    web:
      exposure:
        include: "*"