server:
  port: 29529

spring:
  application:
    name: cloud-gateway29529
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能
      routes:
        - id: cloud-provider-payment28020 #路由id名，需要唯一
          uri: lb://CLOUD-PAYMENT-SERVICE #服务地址
          predicates:
            - Path=/payment/get/** # 断言数组
        - id: cloud-provider-payment28021
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/create

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.2.13:27020/eureka/
  instance:
    instance-id: cloud-gateway29529
    prefer-ip-address: true