server:
  port: 28401

spring:
  application:
    name: sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.13:8848
    sentinel:
      transport:
        dashboard: 192.168.2.13:28080
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: '*'