server:
  port: 23344

spring:
  application:
    name: cloud-config-center23344
  cloud:
    config:
      server:
        git:
          uri: https://github.com/madokast/JavaLearn2020.git
          search-paths:
            - springcloud20200413/springcloud-config
          skipSslValidation: true
          force-pull: true
      label: master

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.2.13:27020/eureka/

  instance:
    instance-id: config-center23344
    prefer-ip-address: true
