server:
  port: 23344

spring:
  application:
    name: cloud-config-center23344
  cloud:
    config:
      server:
        git:
          uri: https://github.com/madokast/springcloudConfig.git
          search-paths:
            - springcloud-config0428
          skipSslValidation: true
          force-pull: true
      label: master
  rabbitmq:
    host: 192.168.2.3
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.2.13:27020/eureka/

  instance:
    instance-id: config-center23344
    prefer-ip-address: true

# rabbitMQ 暴露bus刷新配置端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"