server:
  port: 27020

eureka:
  instance:
    hostname: 192.168.2.13
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://192.168.2.13:27020/eureka/
  server:
    enable-self-preservation: false