server:
  port: 20090

spring:
  application:
    name: cloud-order-client

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.2.13:27010/eureka/
  instance:
    instance-id: order20090
    prefer-ip-address: true

ribbon:
  # 连接超时
  ConnectTimeout: 5000
  # 响应超时
  ReadTimeout: 5000

feign:
  hystrix:
    enabled: true
