server:
  port: 19002

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.13:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
