server:
  port: 27001

eureka:
  instance:
    hostname: 192.168.2.13
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://192.168.2.3:27002/eureka/
  server:
    enable-self-preservation: false